// <auto-generated />
namespace Seshin.Infratructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedTablesProductColorProductPerfumeSimilarProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedTablesProductColorProductPerfumeSimilarProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202102021449277_Added-Tables-ProductColor-ProductPerfume-SimilarProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
