// <auto-generated />
namespace Seshin.Infratructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UpdatedProductMainFeatureAddedFieldAdditionalInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdatedProductMainFeatureAddedFieldAdditionalInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "202104170511568_Updated-ProductMainFeature-Added-Field-AdditionalInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
